sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t rbadenhorst/docker-reactapp -f Dockerfile.dev .

script:
  - docker run -e CI=true rbadenhorst/docker-reactapp npm run test