sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t rbadenhorst/react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true rbadenhorst/docker-react npm run test