sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t rbadenhorst/docker-reactapp -f Dockerfile.dev .

script:
  - docker run -e CI=true rbadenhorst/docker-reactapp npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-reactapp"
  env: "DockerReactapp-env"
  bucket_name: "elasticbeanstalk-eu-central-1-561622865892"
  bucket_path: "docker-reactapp"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY